### ISSUE TITLE
Add versioning & tagged releases

### ISSUE THREAD

**Issue by bjmc-globus** [globus/globus-cwlogger#14]
At least for the client, it would be easier to install and manage packages that depend on this if there were marked "releases" on github.

**Comment by aaschaer** [comment]
The release branches will be stable, so something like 

`pip install git+https://github.com/globus/globus-cwlogger@release/beta-3#subdirectory=client`

Will always get the same client code

**Comment by sirosen** [comment]
`1.0` was released as a signed tag (and I'd like to tag releases on `master`, a la CLI, SDK, and other projects). I think this satisfies any desire for a tag and published release.
I'm also (as with other projects) filling out a full GitHub release after the tag and putting the changelog in there.
